spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libmanage?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  mail:
    username: 1187893119@qq.com
    password: dmbkiyfihasohddg
    host: smtp.qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl: enable=true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB