spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libmanage?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  mail:
    username: 1187893119@qq.com
    password: dmbkiyfihasohddg
    host: smtp.qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl: enable=true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 100ms #关闭超时时间，默认值100ms
